import Head from 'next/head';
import { AllBlog, BlogBanner } from '../src/components';
import Layout from '../src/components/layout';

export default function Blog() {
  return (
    <>
      <Head>
        <title>Blog - Quality Homes Reimagined, LLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout>
        <BlogBanner />
        <AllBlog />
      </Layout>
    </>
  );
}
