import Head from 'next/head';
import { useState } from 'react';
import {
  Additional,
  Banner,
  ClientReview,
  Feature,
  Houses,
  News,
  Offer,
  Offers,
  ReadyToSell,
  Steps,
  Subcription,
  Trusted,
} from '../src/components';
import Layout from '../src/components/layout';
import Modal from '../src/components/modal';

export default function Home() {
  const [show, setShow] = useState(false);

  return (
    <>
      <Head>
        <title>We Buy Houses Fast For Cash | Quality Homes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout>
        <Modal show={show} setShow={setShow} />
        <Banner />
        <Offer show={show} setShow={setShow} />
        <Trusted />
        <Steps show={show} setShow={setShow} />
        <Feature show={show} setShow={setShow} />
        <ClientReview />
        <Offers />
        <Houses />
        <Additional />
        <ReadyToSell show={show} setShow={setShow} />
        <News />
        <Subcription show={show} setShow={setShow} />
      </Layout>
    </>
  );
}
